### PR TITLE
added helper commands and moved slash definitions to slash blocks

### PR DESCRIPTION
**Pull request by RedMan13**

### CODE REVIEW

**Comment by Malix-Labs** [comment]
Has this been done with s4d ?

**Comment by RedMan13** [comment]
how would there be updates to blocks.xml if it wasnt

**Comment by RedMan13** [comment]
in short yes

**Comment by Malix-Labs** [comment]
> how would there be updates to blocks.xml if it wasnt

True.

**Comment by Malix-Labs** [comment]
Have you tested absolutely everything?

**Comment by RedMan13** [comment]
yes

this code has already been evaluated by @noxyyk and i fixed the found issues

**Pull request merged**
